# Generated by Django 5.1.7 on 2025-08-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0008_remove_examresult_vocab_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningmaterial',
            name='accent',
            field=models.CharField(blank=True, choices=[('british', 'British'), ('american', 'American'), ('australian', 'Australian'), ('canadian', 'Canadian')], max_length=50, null=True),
        ),
    ]
