# Generated by Django 5.1.7 on 2025-08-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0009_alter_listeningmaterial_accent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='total_score',
            field=models.IntegerField(),
        ),
    ]
