# Generated by Django 5.1.7 on 2025-08-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0010_alter_examresult_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='listen_score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='reading_score',
            field=models.IntegerField(),
        ),
    ]
