# Generated by Django 5.1.7 on 2025-08-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0011_alter_examresult_listen_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeningmaterial',
            name='source',
        ),
        migrations.RemoveField(
            model_name='readingpassage',
            name='source',
        ),
    ]
