# Generated by Django 5.1.7 on 2025-08-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0012_remove_listeningmaterial_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option_e_text',
        ),
    ]
