# Generated by Django 5.1.7 on 2025-08-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0013_remove_question_option_e_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='time_limit_enabled',
            field=models.BooleanField(default='True'),
        ),
    ]
