# Generated by Django 5.1.7 on 2025-08-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0014_alter_examsession_time_limit_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='time_limit_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
