# Generated by Django 5.1.7 on 2025-08-12 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0015_alter_examsession_time_limit_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='英文單字')),
                ('pronunciation', models.CharField(blank=True, max_length=100, verbose_name='音標')),
                ('part_of_speech', models.CharField(max_length=50, verbose_name='詞性')),
                ('translation', models.CharField(max_length=255, verbose_name='中文翻譯')),
                ('example_sentence', models.TextField(verbose_name='例句')),
                ('difficulty_level', models.IntegerField(default=1, verbose_name='難度等級')),
                ('related_category', models.CharField(blank=True, max_length=100, verbose_name='主題類別')),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='part',
            field=models.IntegerField(blank=True, choices=[(0, 'All - 綜合測驗'), (2, 'Part 2 - 應答問題'), (3, 'Part 3 - 簡短對話'), (5, 'Part 5 - 句子填空'), (6, 'Part 6 - 段落填空'), (7, 'Part 7 - 單篇閱讀')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='part',
            field=models.IntegerField(blank=True, choices=[(0, 'All - 綜合測驗'), (2, 'Part 2 - 應答問題'), (3, 'Part 3 - 簡短對話'), (5, 'Part 5 - 句子填空'), (6, 'Part 6 - 段落填空'), (7, 'Part 7 - 單篇閱讀')], null=True),
        ),
        migrations.CreateModel(
            name='UserVocabularyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_familiar', models.BooleanField(default=False, verbose_name='是否熟悉')),
                ('last_viewed', models.DateTimeField(auto_now=True, verbose_name='最後檢視時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic.dailyvocabulary', verbose_name='單字')),
            ],
            options={
                'verbose_name': '使用者單字紀錄',
                'verbose_name_plural': '使用者單字紀錄',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
