# Generated by Django 5.1.7 on 2025-08-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0016_dailyvocabulary_alter_exam_part_alter_question_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyvocabulary',
            name='example_translation',
            field=models.TextField(blank=True, null=True, verbose_name='例句翻譯'),
        ),
    ]
