# Generated by Django 5.1.7 on 2025-08-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0017_dailyvocabulary_example_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='learning_interests',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
