# Generated by Django 5.1.7 on 2025-08-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0018_user_learning_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyvocabulary',
            name='related_category',
            field=models.CharField(blank=True, choices=[('Business', '商業與職場'), ('Technology', '科技與資訊'), ('DailyLife', '日常生活'), ('Academic', '學術與教育'), ('Travel', '旅遊與文化')], default='DailyLife', max_length=100, verbose_name='主題類別'),
        ),
    ]
