# Generated by Django 5.2.5 on 2025-08-14 20:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0019_alter_dailyvocabulary_related_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAssignedVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(default=datetime.date.today, verbose_name='分配日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toeic.dailyvocabulary', verbose_name='每日單字')),
            ],
            options={
                'verbose_name': '每日單字分配紀錄',
                'verbose_name_plural': '每日單字分配紀錄',
                'ordering': ['-date_assigned'],
                'unique_together': {('user', 'date_assigned', 'word')},
            },
        ),
    ]
