# Generated by Django 5.2.5 on 2025-08-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0020_dailyassignedvocabulary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyAssignedVocabulary',
        ),
    ]
