# Generated by Django 5.2.5 on 2025-08-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0021_delete_dailyassignedvocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservocabularyrecord',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='單字發送時間'),
        ),
    ]
