# Generated by Django 5.2.5 on 2025-08-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toeic', '0022_uservocabularyrecord_sent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningmaterial',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
